### ISSUE TITLE
Wron façade in documentation

### ISSUE THREAD

**Issue by iamNikitaValty** [joshrainwater/active-users#1]
Hi,

I've install this package in my project but it could not work first when i simply follow install instructions that are in the doc.
The problem was refering to a missing façade.
When i inspected the source code, i found out that you used a different faça de name in the documentation. Especially, you used this 'Active' => Rainwater\Active\ActivityFacade::class instead of your façade that is actually named "ActiveFacade".

I think you used the façade name of the parent project https://github.com/thomastkim/laravel-online-users

Hope u'll correct it in the documentation very soon.

**Comment by joshrainwater** [comment]
Taken care of, thanks for noticing!
